# Generated by Django 2.1.7 on 2019-02-24 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberType', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'DetailMember',
                'verbose_name_plural': 'DetailMembers',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='detailmember',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborations.Post'),
        ),
    ]
