# Generated by Django 2.1.7 on 2019-03-07 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0002_auto_20190305_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberType', models.SmallIntegerField(default=0)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needMember', to='collaborations.Post')),
            ],
            options={
                'verbose_name': 'DetailMember',
                'verbose_name_plural': 'DetailMembers',
            },
        ),
        migrations.RemoveField(
            model_name='detailmember',
            name='postId',
        ),
        migrations.DeleteModel(
            name='DetailMember',
        ),
    ]
