# Generated by Django 2.1.7 on 2019-03-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0003_auto_20190307_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='needmember',
            name='isLive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='isLive',
            field=models.BooleanField(default=True),
        ),
    ]
