# Generated by Django 2.1.7 on 2019-03-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0004_auto_20190307_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needmember',
            old_name='isLive',
            new_name='isRecruit',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='isLive',
            new_name='isRecruit',
        ),
    ]
