# Generated by Django 2.1.7 on 2019-03-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0005_auto_20190307_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='isRecruit',
            new_name='isAlive',
        ),
    ]
