# Generated by Django 2.1.7 on 2019-03-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0006_auto_20190307_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needmember',
            old_name='postId',
            new_name='post',
        ),
    ]
