# Generated by Django 2.1.7 on 2019-03-08 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0009_auto_20190307_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needmember',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='collaborations.Post'),
        ),
    ]
