# Generated by Django 2.1.7 on 2019-04-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='title',
        ),
    ]
