# Generated by Django 2.1.7 on 2019-04-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0004_auto_20190413_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='Vote.Topic'),
        ),
    ]
