# Generated by Django 2.1.7 on 2019-03-20 09:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import room.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='roomscore',
            name='writter',
        ),
        migrations.AddField(
            model_name='room',
            name='writter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomscore',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roomReview', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(null=True, upload_to=room.models.room_photo_path), blank=True, size=None),
        ),
    ]
