# Generated by Django 2.1.7 on 2019-03-21 08:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import room.models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20190320_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(null=True, upload_to=room.models.room_photo_path), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='roomscore',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomReviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
