# Generated by Django 2.1.7 on 2019-03-21 10:43

from django.db import migrations, models
import room.models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20190321_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.FileField(null=True, upload_to=room.models.room_photo_path),
        ),
    ]
